name: TPL Scraper Daily Run

# WORKFLOW DISABLED - Original triggers commented out below
on:
  # This workflow is disabled - using a dummy trigger that will never execute
  workflow_dispatch:
    inputs:
      disabled:
        description: "This workflow is disabled"
        required: false
        default: "true"

# Original triggers (disabled):
# schedule:
#   # Run daily at 9:00 AM UTC (5:00 AM EST / 4:00 AM EDT)
#   - cron: "0 9 * * *"
# workflow_dispatch: # Allow manual triggering

jobs:
  scrape-tpl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create data directory
        run: mkdir -p data

      - name: Download previous data artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: tpl-scraper-data
          path: data/
          if_no_artifact_found: ignore
        continue-on-error: true

      - name: Build TypeScript
        run: npm run build

      - name: Run TPL Scraper
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          NODE_ENV: production
        run: npm start

      - name: Upload data artifact
        uses: actions/upload-artifact@v4
        with:
          name: tpl-scraper-data
          path: data/
          retention-days: 90 # Keep data for 90 days
        if: always() # Upload even if the scraper fails
